[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
authors = [
    { name = "Lucas Colley", email = "lucas.colley8@gmail.com" },
]
name = "pint-array"
description = "Pint quantities with array API standard arrays."
version = "0.1.0"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.dependencies]
pint = ">=0.24.4,<0.25"
array-api-compat = ">=1.10.0,<2"
array-api-strict = ">=2.2,<3"
ipython = ">=8.31.0,<9"

[tool.pixi.pypi-dependencies]
pint-array = { path = ".", editable = true }
